failed_status_test:
  type: bool
  default: false
  description: "Turn on to test statusPage failure"
test_status_message:
  type: string
  default: "System is down!!"
  description: "Message to display when status is down"
minor_status_message:
  type: string
  default: "System encountered a minor error!!"
  description: "Message to display when status is down with a minor indicator."
major_status_message:
  type: string
  default: "System encountered a major error!!"
  description: "Message to display when status is down with a major indicator."
critical_status_message:
  type: string
  default: "System encountered a critical error!!"
  description: "Message to display when status is down with a critical indicator."
status_endpoint:
  type: string
  default: ""
  description: "The `.json` endpoint to make a call to for your sites statusPage. ex. 'https://status.yourWebsite.com/api/v2/status.json'"
status_more_info_link:
  type: string
  default: ""
  description: "Webpage to send users to upon clicking the 'Status Down' alert link."